### ISSUE TITLE
Не работает с кириллическими ссылками

### ISSUE THREAD

**Issue by pythonomorpha** [multiprogramm/ListDownloader#1]
Выдаётся ошибка 900
пример ссылки:
(https://www.geno-dbase.ru/storage/Russian_Empire/Tver/_Плёнки/_2401485 - 2429418 - 499 плёнок/2408348/0597.jpg)

**Comment by multiprogramm** [comment]
Теперь должно скачиваться.

**Comment by pythonomorpha** [comment]
Спасибо за оперативность, с кириллицей вопрос решён

 

Но, похоже, есть ещё проблемы.

Я использую командную строку:

C:\ListDownloader.exe -dir C:\dl_files\ C:\dl_files\url-list.txt

И прилагаемый тестовый файл со ссылками.

Windows 7 х64

 

Проблема 1.

По второй ссылки всегда выдаётся ошибка, хотя она рабочая

 

Проблема 2.        

Оригинальные имена файлов не сохраняются. Имя файл состоит из одного расширения

 

Проблема 3.    

Похоже, файлы перезаписываются один поверх другого и у программы нет аргументов, которые контролируют перезапись.

Вероятно, это следствие проблемы 2. Если бы сохранялись уникальные имена, то не происходило бы и перезаписи

 

Проблема 4.

Добавлен аргумент encoding. Но при вызове помощи или в описании программы не показаны, какие ключи можно с ним использовать

**Comment by multiprogramm** [comment]
По поводу проблемы 2.
Дело в том, что основная идея, с которой создавалась эта программа - больше переименовывалка файлов (когда в комплекте есть нормальные имена), чем качалка. Надо, наверное, нормальную документацию будет сделать с примерами. Т.е. её основная задача - скачать по m3u-файлу mp3-файлы (по ссылкам внутри) и дать им корректные имена (по именам внутри).
Побочная задача, которая решилась заодно - это умение скачивать по txt-файлу, где для каждой ссылки надписано корректное имя. Т.е. файлика вида

Корректное имя 1
https://example.com/1232232/243123123/4644193.mp3
Корректное имя 2
https://example.com/453495834/111/54594.mp3

Но да, возможно и использование в качестве качалки, без надписанных корректных имён, по файлику из одних ссылок. В этом сценарии да, сейчас есть баг по извлечению имени файла из ссылки, я его починю. Я это просто к тому, что это краевой сценарий от побочного :)


По поводу проблемы 3.
Да, всё верно, т.к. неправильно определяются имена из-за проблемы 2, они получаются одинаковыми. Т.к. в основном сценарии работы предполагается, что файлам даются корректные имена, программа предполагает, что у файлов уже будут корректные имена внутри файла-списка, а корректные - это в том числе значит и неповторяющиеся :) Т.е. имя файла считается уникальным, и если такой файл уже существует, то программа считает, что уже его скачала, и переходит к скачке следующего. Это делалось, чтобы можно было скачать половину, вырубить программу, включить - и она докачает только те, что ещё не скачала.

Но, т.к. уникальность имён - это довольно сильное предположение в любом из сценариев, на всякий случай есть ключик -num. Он пронумерует результирующие имена файлов, и тогда результирующее имя станет уникальным в рамках списка. Это я просто говорю на тот случай, что в архивах с www.geno-dbase.ru может быть очень много разных ссылок на разные файлы, которые называться в итоге будут одинаково - как нибудь в стиле "0001.jpg", хотя это будут совершенно разные фотографии из разных папок.

Проблема 4.
Да, проблема документации. Возможные значения этого ключа можно посмотреть вот тут
https://docs.microsoft.com/en-us/dotnet/api/system.text.encoding?view=netframework-4.5.2#list-of-encodings
в столбце Name, и нужно, чтобы в столбце ".NET Framework support" стояла галочка (достаточное, но не необходимое условие).

Проблема 1.
У меня она повторилась как следствие проблемы 2, причём то с первым файлом, то со вторым. Т.к. программа качает в несколько потоков, каждый в свой файл, а файл один и тот же - там, скорее всего, происходит гонка. С уникальными именами и фиксом проблемы 2 должно починиться.

**Comment by multiprogramm** [comment]
Проблему 2 починил, должны уйти 1 и 3. По документации заведу себе задачу.

**Comment by pythonomorpha** [comment]
Да, я понял, что это побочное использование, для которого программа не создавалась. Спасибо, что расширили функционал.

 

Я не был уверен, что ключ –num разумно использовать. Если какой-то файл не скачается, то вся нумерация может сбиться. А в данном случае важно, чтобы номера скаченных файлов точно соответствовали номерам плёнок.

 

Для сайта www.geno-dbase.ru обычно скачивают конкретные папки, так как каждая папка строго соответствует определённому архивному документу. Маловероятно, чтобы кто-то скачивал вперемешку файлы из разных папок. И да, большинство плёнок нумеруется одинаково: от 0001 до последнего. Поэтому  папки будут разными, а номера файлов оодинаковы при этом

**Comment by pythonomorpha** [comment]
Большое спасибо!

Все сработало как часы
